## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
import numpy as np

# Q1-1
df = pd.DataFrame(data)
print("Q1-1\n", df)
# Q1-2
psyORt = df.loc[np.logical_or(df.job=="teacher", df.job =="psychologist"), :]
psyORtCars = psyORt.loc[df.num_cars > df.family_size, :]
print(df)
print("\nQ1-2\n", psyORtCars)
# Q1-3
famMem = df.loc[df.family_size<=2,:]
famMem1Car = famMem.loc[df.num_cars>=1,:]
print("\nQ1-3\n", famMem1Car)
# Q1-4
print('\nQ1-4\nunique jobs:', len(df.job.unique()))

**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
data = {'fruit': fruit, 'weights': weights}
df = pd.DataFrame(data)
for f in df.fruit.unique():
  meanWeight = np.mean(weights)
  print(f, meanWeight)

banana 5.5
carrot 5.5
apple 5.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [9]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [26]:
# Q3-1
sortedC = np.sort(course_name)
for i in sortedC:
  print(np.where(course_name == i))


# Q3-2
for i in course_name:
  nameList = list(i)
  haveORnot = nameList[0]=='P'
  if haveORnot:
    print(i, "starts with \'P\'")
  else:
    print(i, "doesn't start with \'P\'")

(array([1]),)
(array([3]),)
(array([0]),)
(array([2]),)
(array([4]),)
Python starts with 'P'
JS doesn't start with 'P'
examples doesn't start with 'P'
PHP starts with 'P'
html doesn't start with 'P'


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Q4-1
print('original:', student_id,'reversed:',  np.flip(student_id))
# Q4-2
print('\n3-largest values:', sorted(student_id, reverse=True)[:3])

original: [1023 5202 6230 1671 1682 5241 4532] reversed: [4532 5241 1682 1671 6230 5202 1023]

3-largest values: [6230, 5241, 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [28]:
multiples3 = np.arange(3, 100, 3)
sumMul3 = np.sum(multiples3)
multiples5 = np.arange(5, 100, 5)
sumMul5 = np.sum(multiples5)
multiples = sumMul3 + sumMul5
print('sum of all the multiples of 3:', sumMul3)
print('sum of all the multiples of 5:', sumMul5)
print('sum of all the multiples of 3 or 5 below 100:', multiples)
# Hint: you can use arange to start off

sum of all the multiples of 3: 1683
sum of all the multiples of 5: 950
sum of all the multiples of 3 or 5 below 100: 2633


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Q6.1.
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)
# Q6.2.
arr = np.arange(12).reshape(3,4)
arr[[0,1],:] = arr[[1,0], :]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
